### ISSUE TITLE
How to install mORMot in lazarus-2.0.6-fpc-3.0.4-win64?

### ISSUE THREAD

**Issue by zqluo1** [synopse/mORMot#321]
Compile package mormot_base 1.18: Exit code 1, Errors: 8, Warnings: 3
SynCommons.pas(7332,23) Warning: Some fields coming after "" were not initialized
SynCommons.pas(13807,42) Warning: Some fields coming after "VType" were not initialized
SynCommons.pas(15370,56) Warning: Some fields coming after "VOptions" were not initialized
SynFPCTypInfo.pas(91,31) Error: Identifier not found "PInterfaceData"
SynFPCTypInfo.pas(91,45) Error: Error in type definition
SynFPCTypInfo.pas(92,32) Error: Identifier not found "PVmtMethodParam"
SynFPCTypInfo.pas(92,47) Error: Error in type definition
SynFPCTypInfo.pas(93,33) Error: Identifier not found "PIntfMethodTable"
SynFPCTypInfo.pas(93,49) Error: Error in type definition
SynFPCTypInfo.pas(94,33) Error: Identifier not found "PIntfMethodEntry"
SynFPCTypInfo.pas(94,49) Error: Error in type definition

**Comment by pavelmash** [comment]
mORMot need an RTTI features introduced by FPC 3.2
Recommended FPC version is FPC 3.2 rc1 (while we do noh have a 3.2 release)
see (this forim topic)[https://synopse.info/forum/viewtopic.php?id=5361] for details
