### ISSUE TITLE
Delphi 2007:  not defined USHORT

### ISSUE THREAD

**Issue by pult** [synopse/mORMot#323]
SynCrtSock.pas - not defined USHORT for old delphi

Fix:
`PackageNameLength: {+}{$if declared(USHORT)}USHORT{$else}Word{$ifend}{+.};
`

**Comment by synopse** [comment]
Fixed by https://github.com/synopse/mORMot/commit/7ef4a849cb0571e4d6604b86c88017e48158054b

It was introduced by a third-party pull request.
Sorry.
