### ISSUE TITLE
The last ')' is missed.

### ISSUE THREAD

**Issue by pankey888** [synopse/mORMot#347]
When did something like this:
TSQLSampleRecord.AutoFree(Rec, Database, '(ID in (1,2) or ID in (3,4))', []);
the sql clause became:  'select ID,Time,Name,Question from SampleRecord where (ID in (1,2) or ID in (3,4)'. I fixed it like this (SynTable.pas, GetWhereExpression):

'n','N': begin
       Where.Operator := opIn;
       P := GotoNextNotSpace(P+2);
       if P^<>'(' then
         exit; // incorrect SQL statement
       B := P; // get the IN() clause as JSON
       inc(P);
       while (P^<>')') or (P[1]=':') do // handle :(...): within the clause
         if P^=#0 then
           exit else
           inc(P);
       inc(P);
       SetString(Where.Value,PAnsiChar(B),P-B);
       Where.ValueSQL := B;
       Where.ValueSQLLen := P-B;
       result := GetWhereValues(Where);
       **P := GotoNextNotSpace(P);
        if (P^=')') and (Where.FunctionName='') then begin
          B := P;
          repeat
            inc(P);
          until not (P^ in [#1..' ',')']);
          while P[-1]=' ' do dec(P); // trim right space
          SetString(Where.ParenthesisAfter,B,P-B);
          P := GotoNextNotSpace(P);
        end;**
       exit;
    end;

**Comment by synopse** [comment]
This parser is not full SQL-compliant yet - it is documented as such.
The parser doesn't support nested parenthesis at all.
It would need a recursive algorithm for proper implementation, which is not done yet.
I guess you could just not write the main parenthesis.

**Comment by synopse** [comment]
Please use our forum first before creating an issue in github.
Discussion is better on the forum, since it may help other users to find the information later on.
https://synopse.info/forum/viewforum.php?id=2
