### ISSUE TITLE
SynDBUniDAC.pas has errors

### ISSUE THREAD

**Issue by wxinix** [synopse/mORMot#350]
1. The interface USES section should include SynTable and SynOleDB - these two are missing.
2. Line 287 missing the **;** statement terminator
meta.Restrictions.Values['TABLE_SCHEMA'] := UTF8ToString(UpperCase(Owner)) 

It won't compile without the above fix.

**Comment by synopse** [comment]
Why is SynOleDB needed? They should not be related.

I guess line 287 there is a "else" missing, not a ';'.

Please check the fix.

**Comment by wxinix** [comment]
> Why is SynOleDB needed? They should not be related.
It is needed because of:
Line 437: CoInit
Line 521: CoUninit

**Comment by wxinix** [comment]
It is still not fixed.  The missing unit is SynOleDB,  NOT OleDB
You added OleDB, which still doens't compile! 
I am confused (or more of a shock) - when you make changes, you don't do any testing, or at least a test-compile?

**Comment by synopse** [comment]
I am sorry, I don't have any UniDAC licence on my current computer any more.
Therefore I do such mistakes and can't test this unit.
Perhaps the easiest and safest is to provide a pull request from your working code.

**Comment by wxinix** [comment]
> Therefore I do such mistakes and can't test this unit.
> Perhaps the easiest and safest is to provide a pull request from your working code.
Understand.  I am still on the learning curve of the great mORMot. I'll try to be helpful.  It it amazing to see how fast mORMot performs.    Thank you, AB.
