### ISSUE TITLE
Strange behaviour

### ISSUE THREAD

**Issue by Rura1980** [synopse/mORMot#357]
Hello.
I have the following problem.I compile and run mormot http server on port X using delphi 10.4.1.
When I start accidentally 2 http servers on the same port, mormot allows me to do that. 
The exception is raised, but it somehow is ignored. 
Is it an intended behaviour? Can I somehow check in my code, that mormot http server was started succefully?

Thank You.

**Comment by synopse** [comment]
Hello.
This is a bit difficult to find out what you expect.

Please use the forum first https://synopse.info/forum to state your problem.
And include some reproducible code, not within the thread, but as gist.
