### ISSUE TITLE
Use fully qualified namespaces

### ISSUE THREAD

**Issue by SteveNew** [synopse/mORMot#366]
At least on the Delphi side this is more and more considered best practice - and it is a pain to update these manually every time we update mORMot - hopefully this is the norm in mORMot2 - with all the other great "cleanups" :)

Thanks

**Comment by synopse** [comment]
It is a fair but too broad issue for sure.
Please use the forum to discuss about it.

**Comment by SteveNew** [comment]
Thanks Arnaud - I will.
