### ISSUE TITLE
syncommons.pos is 5x slower than system.pos

### ISSUE THREAD

**Issue by bleuge** [synopse/mORMot#367]
Hi, I remembered Mormot had a faster Pos function. I was doing really a lot of Pos in some code while bruteforcing some compression code. Changing system.pos for syncommons.pos make it 5x slower. Both string and substring to search are declared as ansistrings. 
Is this normal?

**Comment by synopse** [comment]
Please don't use github issues for such discussion.
Use https://synopse.info/forum/viewforum.php?id=2 for discussion.

I guess you mean PosEx() use of SynCommons.
It only expects RawUTF8 parameters, so the compiler will emit a warning if you use it, and make a memory allocation.
So it is expected to be slower. It should work on RawUTF8/RawByteString/AnsiString only.

For the string=UnicodeString function, you should use PosExString().
