### ISSUE TITLE
AV exception raised when SQL user login failed. SynDB

### ISSUE THREAD

**Issue by cykevinc** [synopse/mORMot#368]
I tried the code:
aConProp:=TSQLDBZEOSConnectionProperties.Create(
				TSQLDBZEOSConnectionProperties.URI('OleDB[mssql]', '', ''),
				Format(csConStr,[aSQLServer,aDatabase]),aLogin,aPWD);
try
  aStmt:=aConProp.NewThreadSafeStatementPrepared(csSQL,True,True);
  aStmt.Bind([aUserID]);
  aStmt.ExecutePrepared;
  if aStmt.Step then 
	 aName:=aStmt.ColumnString(0);
except
  On E: Exception do begin
	TSynLog.Add.Log(sllServer,'Connect failed :% ',[E.Message]);
	raise
  end;
end;

It shows AV message instead of "OLEDB Error 80040E4D: SQLState: Login failed for user..." when user login denied.

I noticed when login denied the Stmt instance will be nil but still be referenced in exception block.

I revised TryPrepare procedure exception block like below and then works fine. Hope this can help.

  procedure TryPrepare(doraise: boolean);
  var Stmt: TSQLDBStatement;
  begin
     ....
    except
      on E: Exception do begin
        StringToUTF8(E.Message,fErrorMessage);
        fErrorException := PPointer(E)^; 
        if assigned(Stmt) then begin
           {$ifndef SYNDB_SILENCE}
           with SynDBLog.Add do
             if [sllSQL,sllDB,sllException,sllError]*Family.Level<>[] then
               LogLines(sllSQL,pointer(Stmt.SQLWithInlinedParams),self,'--');
           {$endif}
           Stmt.Free;
        end else
           with SynDBLog.Add do
              if [sllSQL,sllDB,sllException,sllError]*Family.Level<>[] then
               LogLines(sllSQL,pointer(fErrorMessage),self,'--');
        result := nil;
        if doraise then
          raise;
      end;

**Comment by synopse** [comment]
Please use the mORMot forum for such discussion.
https://synopse.info/forum/viewforum.php?id=2
Do not create a ticket directly.
