### ISSUE TITLE
Update SynDB unit ( TQuery FPC compatibility )

### ISSUE THREAD

**Issue by tidawsiwin** [synopse/mORMot#372]
I use Lazarus 2.0.10 with FPC 3.2.0.
While using mORMot with TQuery, I constat that the function 
`TQuery.FieldByName('ffield').AsString;
TQuery.FieldByName('ffield').AsWideString;
`
returns bad when it encounters accent characters ( é, à, è, ... ).
So I have bypassed this problem with the following modifications in the code in SynDB.pas :
`
function TQueryValue.GetAsWideString: SynUnicode;
begin
  CheckValue;
  with TVarData(fValue) do
  case VType of
    varNull:     result := '';
    varInt64:    result := UTF8ToSynUnicode(Int64ToUtf8(VInt64));
    {$ifdef fpc}
    varString:   result := WideString(RawUTF8(VAny));//UTF8ToSynUnicode(RawUTF8(VAny));
    {$else}
    varString:   result := UTF8ToSynUnicode(RawUTF8(VAny));
    {$endif}
    {$ifdef HASVARUSTRING}
    varUString:  result := UnicodeString(VAny);
    {$endif}
  else Result := SynUnicode(fValue);
  end;
end;  
` 
and : 
`
function TQueryValue.GetString: string;
begin
  CheckValue;
  with TVarData(fValue) do
  case VType of
    varNull:     result := '';
    varInteger:  result := IntToString(VInteger);
    varInt64:    result := IntToString(VInt64);
    varCurrency: result := Curr64ToString(VInt64);
    varDouble:   result := DoubleToString(VDouble);
    varDate:     result := Ansi7ToString(DateTimeToIso8601Text(VDate,' '));
    {$ifdef FPC}
    varString:   result := String(RawUTF8(VAny)); //UTF8ToString(RawUTF8(VAny));
    {$else}
    varString:   result := UTF8ToString(RawUTF8(VAny));
    {$endif}
    {$ifdef HASVARUSTRING}
    varUString:  result := string(UnicodeString(VAny));
    {$endif HASVARUSTRING}
    varOleStr:   result := string(WideString(VAny));
    else result := fValue;
  end;
end;       
`
So If you find that my corrections are correct, It will be geat to incorporaate them.
Thanks.

PS: github is not formatting code correctelly.

**Comment by synopse** [comment]
Please use the forum on synopse.info to discuss this, and use http://gist.github.com/ to post some code, or even better make a pull request on github.

**Comment by pavelmash** [comment]
Use a three back quotes to format come (I reformat it correctly)

**Comment by synopse** [comment]
Furthermore, I don't understand what is wrong with UTF8ToSynUnicode and UTF8ToString in the FPC context.
