### ISSUE TITLE
Annoying C++ hints because of the overloaded create.

### ISSUE THREAD

**Issue by attikov** [synopse/mORMot#373]
Please roll back the overloaded constructors. Really annoying.

**Comment by synopse** [comment]
Please use the forum on synopse.info to discuss.

Renaming the overloaded constructors would break existing user code.

Isn't there any conditional to disable the hints for C++?

**Comment by attikov** [comment]
I'm not discussing, I'm reporting an issue.
I'm tired altering every project settings to suppress this message.
Never mind, I'm looking for alternatives already.

**Comment by synopse** [comment]
I didn't use C++ so I don't know how to be sure the hints are disabled.

**Comment by attikov** [comment]
Me neither, this is a Delphi problem, the warning is by default on, you should have seen it too.

**Comment by synopse** [comment]
I don't have any warning here when I compile with several versions of Delphi - from Delphi 6 to Delphi 10.4.1.
There is no warning when you compile mORMot.
Which compiler are you using?

As you can see, it is a real discussion. ;)

**Comment by synopse** [comment]
The problem is a Delphi problem.

You need to add in your DPR:
{$WARN DUPLICATE_CTOR_DTOR OFF}

It is done automatically if you include, as proposed in the doc and the samples:
program ...

uses
  {$I SynDprUses.inc}
  SysUtils, 
   ....

Because   {$I SynDprUses.inc}  includes this unit.

**Comment by synopse** [comment]
A quick search in the forum:
https://synopse.info/forum/viewtopic.php?id=4128
https://synopse.info/forum/viewtopic.php?id=2627

and so on...
