### ISSUE TITLE
Missing types from generated wrapper

### ISSUE THREAD

**Issue by MrWaz** [synopse/mORMot#381]
With latest versions, I face some issues when generating code wrappers to access my SOA interfaces.

Some types are missing from methods' signature.

e.g. 

`function ValidateUserLogin(const inUserName, inUserPassword: String; out outUserInfo: TMyUserInfo): Boolean;`

is wrapped as
 
`function ValidateUserLogin(const inUserName, inUserPassword: String; out outUserInfo: ): Boolean; `

After narrowing the issue with git bisect, it seems I found the culprit.

in SQLite3/mORMotWrappers.pas, inside TWrapperContext.ContextFromInfo(),  around line 948

`trimcopy(typName,i+1,maxInt,typName);`

the same string is passed as const & out parameter and gets cleared when entering trimcopy.

FYI I'm using delphi 10.1

all the best
Sylvain

**Comment by synopse** [comment]
Should be fixed now.

Thanks for the feedback!

**Comment by MrWaz** [comment]
Thank you for the quick fix

regards
S.
