### ISSUE TITLE
Allow for RESTFul authentication using POST method

### ISSUE THREAD

**Issue by Mane75** [synopse/mORMot#382]
It would be nice to have the option to initiated a RESTFul authentication using POST in addition, instead of just the GET method.

**Comment by synopse** [comment]
I suppose POST works too.
You can try to put the parameters in the POST body, as APPLICATION/X-WWW-FORM-URLENCODED content type.

**Comment by synopse** [comment]
I suppose POST works too.
You can try to put the parameters in the POST body, as APPLICATION/X-WWW-FORM-URLENCODED content type.

**Comment by Mane75** [comment]
Ab, 

I just tried your suggestion and added a Contenty-type: APPLICATION/X-WWW-FORM-URLENCODED header to the POST request and I do get 401-Unauthorized response.

Apparently, some code in TSQLRestServerURIContext.ExecuteCommand flags the request as invalid when it is originate as a POST request.

**Comment by synopse** [comment]
Could you use the debugger and find exactly where TSQLRestServerURIContext.ExecuteCommand the GET is requested?

**Comment by synopse** [comment]
No feedback given in time.

Please reopen if needed.
