### ISSUE TITLE
SQLite 3.35.0 has been released, bringing many powerful functions

### ISSUE THREAD

**Issue by dbyoung720** [synopse/mORMot#388]
SQLite 3.35.0 has been released, bringing many powerful functions

**Comment by synopse** [comment]
Yes, I know.
3.35.0 was buggy; now we have 3.35.1.
I am currently working on libdeflate and quickjs which will need new static binaries, so SQlite3 will be upgraded at the same time.

This has already been already discussed in our forum.
https://synopse.info/forum/viewtopic.php?pid=34596#p34596
