### ISSUE TITLE
SynECC github reference in header seems incorrect

### ISSUE THREAD

**Issue by EricGrange** [synopse/mORMot#398]
The comments say

>   Using secp256r1 curve from "simple and secure ECDH and ECDSA library"
>   Copyright (c) 2013, Kenneth MacKay - BSD 2-clause license
>   https://github.com/esxgx/easy-ecc

but the actual repository seems to be

https://github.com/kmackay/micro-ecc

**Comment by edwinyzh** [comment]
I checked my local copy of easy-ecc, it was correct, but somehow the original repository was removed.

**Comment by synopse** [comment]
Thanks for the feedback.
