### ISSUE TITLE
I have modified/corrected some code but I can't share my work...

### ISSUE THREAD

**Issue by David-Nardi** [synopse/mORMot#416]
Hello, I have modified some units for Alexendria compatiblity  and critical section approch bug.
Here my modification.
+ SynCrtSock : i have only move sone part of code to gain access to WinHttp.
+ SynCommons : use an Integer instead of boolean for fLocked and correct approch to TSynLocker.TryLock !!!
+ Synopse.inc : add support of Delphi 11.

[mORMot.zip](https://github.com/synopse/mORMot/files/7642533/mORMot.zip)
.

**Comment by synopse** [comment]
You started from an very old version of mORMot.
I am unable to find out what needs to be changed in the current trunk.

Please synch with the latest mORMot trunk revision from github, and make a pull request.

**Comment by David-Nardi** [comment]
OK

**Comment by synopse** [comment]
I have fixed TSynLocker with https://github.com/synopse/mORMot/issues/416

For the other stuff, either fork and make a pull request here, or discuss in our forum, putting some code in a Gist.
