### ISSUE TITLE
Typo in SAD 1.18

### ISSUE THREAD

**Issue by the-Arioch** [synopse/mORMot#427]
11.1. Client-Server cheat sheet

https://synopse.info/files/html/Synopse%20mORMot%20Framework%20SAD%201.18.html#TITL_204

>  Beware ... Security/design flows

should be: flAws not flOws

**Comment by the-Arioch** [comment]
Oh, by the way, was there code in mORMot REST server to only be run on Windows when TCP request comes in? Something like xinet.d but for Windows?

Generic search i did point to IIS components Windows Process Activation Service and WWW Publishing Service, but i'd prefer do have no IIS dependencies but http.sys driver

SCM trigger API seems also have no generic "incoming connection" type of triggers, only something very specific and mostly undocumented about RPC and named-pipes.

**Comment by synopse** [comment]
Typo fixed. 

I don't know about XINET equivalency. 
Only reference I found was.... your own question on SO! https://stackoverflow.com/q/71768008/458259 :(
