### ISSUE TITLE
why cannot run the same SQLite on Linux at the same time

### ISSUE THREAD

**Issue by scutlemon** [synopse/mORMot#428]
I use Delphi program to open SQLite database with TSQLRestServerDB. Lockingmode: = lmnormal. The compiler runs on Linux. When the second program is opened, an error is reported: esqlite3exception {"errorcode": 26, "sqlite3errorcode": "secnotadb", "message": "error sqlite_notadb (26) [dbopen] using 3.34.1 with ADB = nil"}. 

But it is possible to run on windows.

What is the matter? How should it be solved?

**Comment by synopse** [comment]
Discussed on the forum.
