### ISSUE TITLE
Forward slash instead of backslash?

### ISSUE THREAD

**Issue by Jawfin** [synopse/mORMot#431]
https://github.com/synopse/mORMot/blob/34bf46e37bb7d2b4dc91adaa4cbdc73e0106a429/SynZip.pas#L1010

I'm no expert, but it seems that last character '\\' should be '/'.
https://sourceforge.net/p/sevenzip/discussion/45797/thread/30a0833bc9/?limit=25#135d
7Zip doesn't handle the \ and replaces it with a unicode dot instead of handling it as a sub-folder.

**Comment by Jawfin** [comment]
Cheers!
I just changed that character for mine!!
Looking forwards to seeing mORMOt 2 going stable :)

**Comment by synopse** [comment]
should be good now.

Please reopen a new ticket on any new issuE.
