### ISSUE TITLE
THttpServer : Executing the HEAD request will read the entire file

### ISSUE THREAD

**Issue by ysair** [synopse/mORMot#441]
Performance will be affected when the file is large, e.g.
HEAD http://localhost/bigfile.json

HTTP/1.0 200 OK
X-Powered-By: mORMot 1.18 synopse.info
Server: mORMot (Windows)
Content-Length: 28373948

```pascal
procedure THttpServer.Process(ClientSock: THttpServerSocket;
  ConnectionID: THttpServerConnectionID; ConnectionThread: TSynThread);

...

    if (ctxt.OutContent<>'') and (ctxt.OutContentType=HTTP_RESP_STATICFILE) then
      try
        ExtractNameValue(ctxt.fOutCustomHeaders,'CONTENT-TYPE:',ctxt.fOutContentType);
        fn := {$ifdef UNICODE}UTF8ToUnicodeString{$else}Utf8ToAnsi{$endif}(ctxt.OutContent);
        if not Assigned(fOnSendFile) or not fOnSendFile(ctxt,fn) then begin
          fs := TFileStream.Create(fn,fmOpenRead or fmShareDenyNone);
          try
            SetString(ctxt.fOutContent,nil,fs.Size);
            fs.Read(Pointer(ctxt.fOutContent)^,length(ctxt.fOutContent));  //reading file content is slow
         finally
            fs.Free;
          end;
         end;
```

**Comment by synopse** [comment]
Nice!

Only caveat: the file response could come from a POST, not only a GET.
So in my fix, I check for 'HEAD' - and use TFileStream.Size which is good enough for our purpose.

**Comment by synopse** [comment]
A fix was needed for mORMot 2 too.
https://github.com/synopse/mORMot2/commit/0a92cb0e

We can see that the new code was easier to fix, because better organized.
A single fix is done for both THttpServer and THttpAsyncServer, which share the same HTTP response logic.

**Comment by ysair** [comment]
Great work!
