### ISSUE TITLE
Cannot compile under Delphi 12 due to the compiler errors

### ISSUE THREAD

**Issue by myonlylonely** [synopse/mORMot#448]
Cannot compile under Delphi 12, the compiler throws an error:
```
[dcc32 Error] SynCrtSock.pas(5381): E1012 Constant expression violates subrange bounds
```
It seems this is no longer valid under Delphi 12.
```pascal
Handle := -1;
```
We could change that to:
```pascal
Handle := THandle(-1);
```

There are 2 lines in `SynCrtSock.pas` we should change: `TCrtSocket.CreateSockIn` and `TCrtSocket.CreateSockOut`

**Comment by synopse** [comment]
Please try with the last commit.

Just a backport what we did in mORMot 2.

**Comment by myonlylonely** [comment]
Yes, that fixed the compile issue.
