### ISSUE TITLE
SynBloomFilter large volumes

### ISSUE THREAD

**Issue by Uefi1** [synopse/mORMot#450]
Hello, can I make a bloomfilter for any huge amount of data?

```
var
BloomFilter:TSynBloomFilter;

procedure Duplicates;
var
I:integer;
s:string;
begin 
for i:=0 to maxint do begin
s:=inttostr(Random(999999)+99999));
if not StrDictionary.MayExist(s) then
StrDictionary.Insert(s);
end;
end;


begin
Randomize;
BloomFilter:=TSynBloomFilter.Create(10000000);
Duplicates;
end;
```

It just seems to me that I'm doing something wrong: Bloomfilter does a very good job with small data, but outright lies with huge data

**Comment by synopse** [comment]
I can't understand your exact concern.

Please use the forum to discuss this.
